# Generated by Django 5.0.4 on 2024-04-27 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField()),
                ('enfermedades', models.TextField()),
                ('medicamentos', models.TextField()),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'expediente',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('microchip', models.CharField(max_length=50)),
                ('caracteristicas', models.TextField()),
                ('imagen1', models.CharField(max_length=50)),
                ('imagen2', models.CharField(max_length=50)),
                ('imagen3', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('cedula_profesional', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('codigo_postal', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'propietario',
            },
        ),
        migrations.CreateModel(
            name='Eutanasia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Eutanasia',
                'verbose_name_plural': 'Eutanasias',
                'db_table': 'eutanasia',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('resultado', models.TextField()),
                ('imagen', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'db_table': 'estudio',
            },
        ),
        migrations.CreateModel(
            name='Desparasitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('proxima_fecha', models.DateField()),
                ('imagen', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Desparasitacion',
                'verbose_name_plural': 'Desparasitaciones',
                'db_table': 'desparasitacion',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia_cardiaca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia_respiratoria', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consulta',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Cirugia',
                'verbose_name_plural': 'Cirugias',
                'db_table': 'cirugia',
            },
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ingreso', models.DateField()),
                ('alta', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Hospitalizacion',
                'verbose_name_plural': 'Hospitalizaciones',
                'db_table': 'hospitalizacion',
            },
        ),
        migrations.CreateModel(
            name='Incineracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Incineracion',
                'verbose_name_plural': 'Incineraciones',
                'db_table': 'incineracion',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.propietario'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.propietario'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.consulta')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'receta',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.receta')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='RecetaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.receta')),
            ],
            options={
                'verbose_name': 'RecetaImagen',
                'verbose_name_plural': 'RecetaImagenes',
                'db_table': 'receta_imagen',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('proxima_fecha', models.DateField()),
                ('imagen', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'db_table': 'vacuna',
            },
        ),
    ]
