# Generated by Django 5.0.4 on 2024-04-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_alter_mascota_imagen1_alter_mascota_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
